[tox]
envlist = py310,py311,py312,py313,py314,sdist,lint
requires =
    tox>4

[gh]
python =
    3.14 = py314
    3.13 = py313
    3.12 = py312, sdist, lint
    3.11 = py311
    3.10 = py310

[testenv]
package = wheel
deps =
    pytest==8.4.2
    ./tests/injection
commands = pytest tests {posargs}

[testenv:sdist]
package = sdist

[testenv:lint]
deps =
    mypy==1.18.2
    # For linting tests
    pytest==8.4.2
commands = mypy tests pyinjector --exclude tests/injection
