from typing import Any, Optional, Tuple
from sys import platform


class Injector:
    def __init__(self) -> None: ...
    def attach(self, pid: int) -> None: ...
    def inject(self, path: bytes) -> int: ...
    def uninject(self, handle: int) -> None: ...
    def detach(self) -> None: ...
    if platform == "linux":
        def inject_in_cloned_thread(self, path: bytes) -> int: ...
    if platform == "linux" or platform == "win32":
        def remote_func_addr(self, handle: int, name: str) -> int: ...
        def remote_call(self, func_addr: int, *args: int) -> int: ...
    if platform == "linux" or platform == "darwin":
        def call(self, handle: Any, name: str) -> None: ...


class InjectorException(Exception):
    args: Tuple[str, int, Optional[str]]
